import mongoose from 'mongoose';

const ObjectId = mongoose.Schema.Types.ObjectId;

const institutionSchema = mongoose.Schema(
  {
    name: { // institution name
      type: String 
    },
    typeOf: { // the type of the institution, for example, primary, high school etc.
      type: String 
    },
    code: { // joining code for the students, autogenerated and must be unique!
      type: String,
      index: true 
    },
    moderatorCode: { // joining code for the moderators
      type: String,
      index: true
    },
    departments: { // list of the departments of the institution
      type: [ String ]
    },
    deleted: { // is institution deleted
      type: Boolean,
      default: false
    },
    createdBy: { // super-admin of the institution
      type: ObjectId
    }
  }, 
  {
    timestamps: true
  }
);

const Institution = mongoose.model('Institution', institutionSchema);

export default Institution;